# Recursive Solution

In [1]:
import numpy as np

In [2]:
def findContiguousColor(arrayOfPic, xSeed, ySeed, findColor):

##    print("Array:", xSeed, ySeed, arrayOfPic[xSeed][ySeed])
    
    #If the color has changed get out
    if arrayOfPic[xSeed][ySeed] != findColor:
        return;
    
    #Print this cell
    if arrayOfPic[xSeed][ySeed] == findColor:
        arrayOfPic[xSeed][ySeed] = 2 * findColor # Change the color so that we don't go into a recursive loop
        print("(", xSeed, ",", ySeed, ")")
    
    if xSeed > 0:
        findContiguousColor(arrayOfPic, xSeed - 1, ySeed, findColor)
        
    if ySeed > 0:
        findContiguousColor(arrayOfPic, xSeed, ySeed - 1, findColor)
        
    if xSeed < len(arrayOfPic) - 1:
        findContiguousColor(arrayOfPic, xSeed + 1, ySeed, findColor)
    
    if ySeed < len(arrayOfPic[xSeed]) - 1:
        findContiguousColor(arrayOfPic, xSeed, ySeed + 1, findColor)

In [3]:
inputArray = [[1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2],
          [1, 2, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2],
          [2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2],
          [2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 5],
          [1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 5],
          [1, 2, 2, 1, 1, 2, 1, 1, 2, 5, 5, 5],
          [1, 2, 2, 1, 2, 2, 1, 1, 2, 5, 1, 2],
          [2, 1, 2, 1, 1, 2, 1, 5, 5, 5, 1, 2],
          [2, 1, 2, 1, 2, 2, 1, 5, 2, 1, 1, 2],
          [1, 1, 2, 1, 1, 5, 5, 5, 2, 1, 1, 2],
          [1, 2, 2, 1, 1, 5, 1, 1, 2, 1, 1, 2],
          [1, 2, 2, 5, 5, 5, 1, 1, 2, 1, 1, 2],
          [2, 1, 2, 5, 1, 2, 1, 1, 2, 1, 1, 2],
          [2, 5, 5, 5, 2, 2, 1, 1, 2, 1, 1, 2],
          [2, 5, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2],
          [5, 5, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2],
          [2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2],
          [1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2]]

In [4]:
print(len(inputArray))
print(len(inputArray[0]))

18
12


In [5]:
findContiguousColor(inputArray, xSeed = 13, ySeed = 3, findColor = 5)

( 13 , 3 )
( 12 , 3 )
( 11 , 3 )
( 11 , 4 )
( 11 , 5 )
( 10 , 5 )
( 9 , 5 )
( 9 , 6 )
( 9 , 7 )
( 8 , 7 )
( 7 , 7 )
( 7 , 8 )
( 7 , 9 )
( 6 , 9 )
( 5 , 9 )
( 5 , 10 )
( 5 , 11 )
( 4 , 11 )
( 3 , 11 )
( 13 , 2 )
( 13 , 1 )
( 14 , 1 )
( 15 , 1 )
( 15 , 0 )


In [6]:
# Look for the 10s
print(np.matrix(inputArray))

[[ 1  1  2  1  1  2  1  1  2  1  1  2]
 [ 1  2  2  1  2  2  1  1  2  1  1  2]
 [ 2  1  2  1  1  2  1  1  2  1  1  2]
 [ 2  1  2  1  2  2  1  1  2  1  1 10]
 [ 1  1  2  1  1  1  1  1  2  1  1 10]
 [ 1  2  2  1  1  2  1  1  2 10 10 10]
 [ 1  2  2  1  2  2  1  1  2 10  1  2]
 [ 2  1  2  1  1  2  1 10 10 10  1  2]
 [ 2  1  2  1  2  2  1 10  2  1  1  2]
 [ 1  1  2  1  1 10 10 10  2  1  1  2]
 [ 1  2  2  1  1 10  1  1  2  1  1  2]
 [ 1  2  2 10 10 10  1  1  2  1  1  2]
 [ 2  1  2 10  1  2  1  1  2  1  1  2]
 [ 2 10 10 10  2  2  1  1  2  1  1  2]
 [ 2 10  2  1  2  2  1  1  2  1  1  2]
 [10 10  2  1  2  2  1  1  2  1  1  2]
 [ 2  1  2  1  2  2  1  1  2  1  1  2]
 [ 1  1  2  1  1  1  1  1  2  1  1  2]]


In [7]:
inputArray2 = [[1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2],
          [1, 2, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2],
          [2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2],
          [2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 5],
          [1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 5],
          [1, 2, 2, 1, 1, 2, 1, 1, 2, 5, 5, 5],
          [1, 2, 2, 1, 2, 2, 1, 1, 2, 5, 1, 2],
          [2, 1, 2, 1, 1, 2, 1, 5, 5, 5, 1, 2],
          [2, 1, 2, 1, 2, 2, 1, 5, 2, 1, 1, 2],
          [1, 1, 2, 1, 1, 5, 5, 5, 2, 1, 1, 2],
          [1, 2, 2, 1, 1, 5, 1, 1, 2, 1, 1, 2],
          [1, 2, 2, 5, 5, 5, 1, 1, 2, 1, 1, 2],
          [2, 1, 2, 5, 1, 2, 1, 1, 2, 1, 1, 2],
          [2, 5, 2, 5, 2, 2, 1, 1, 2, 1, 1, 2],
          [2, 5, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2],
          [5, 5, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2],
          [2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2],
          [1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2]]

In [8]:
findContiguousColor(inputArray2, xSeed = 13, ySeed = 3, findColor = 5)

( 13 , 3 )
( 12 , 3 )
( 11 , 3 )
( 11 , 4 )
( 11 , 5 )
( 10 , 5 )
( 9 , 5 )
( 9 , 6 )
( 9 , 7 )
( 8 , 7 )
( 7 , 7 )
( 7 , 8 )
( 7 , 9 )
( 6 , 9 )
( 5 , 9 )
( 5 , 10 )
( 5 , 11 )
( 4 , 11 )
( 3 , 11 )


In [9]:
# Look for the 10s
print(np.matrix(inputArray2))

[[ 1  1  2  1  1  2  1  1  2  1  1  2]
 [ 1  2  2  1  2  2  1  1  2  1  1  2]
 [ 2  1  2  1  1  2  1  1  2  1  1  2]
 [ 2  1  2  1  2  2  1  1  2  1  1 10]
 [ 1  1  2  1  1  1  1  1  2  1  1 10]
 [ 1  2  2  1  1  2  1  1  2 10 10 10]
 [ 1  2  2  1  2  2  1  1  2 10  1  2]
 [ 2  1  2  1  1  2  1 10 10 10  1  2]
 [ 2  1  2  1  2  2  1 10  2  1  1  2]
 [ 1  1  2  1  1 10 10 10  2  1  1  2]
 [ 1  2  2  1  1 10  1  1  2  1  1  2]
 [ 1  2  2 10 10 10  1  1  2  1  1  2]
 [ 2  1  2 10  1  2  1  1  2  1  1  2]
 [ 2  5  2 10  2  2  1  1  2  1  1  2]
 [ 2  5  2  1  2  2  1  1  2  1  1  2]
 [ 5  5  2  1  2  2  1  1  2  1  1  2]
 [ 2  1  2  1  2  2  1  1  2  1  1  2]
 [ 1  1  2  1  1  1  1  1  2  1  1  2]]
