In [1]:
import numpy as np

In [2]:
def findContiguousColor(arrayOfPic, xSeed, ySeed, findColor):

##    print("Array:", xSeed, ySeed, arrayOfPic[xSeed][ySeed])
    
    #If the color has changed get out
    if arrayOfPic[xSeed][ySeed] != findColor:
        return;
    
    #Print this cell
    if arrayOfPic[xSeed][ySeed] == findColor:
        arrayOfPic[xSeed][ySeed] = 2 * findColor # Change the color so that we don't go into a recursive loop
        print("(", xSeed, ",", ySeed, ")")
    
    if xSeed > 0:
#        print("Here 1:", xSeed, ySeed)
        findContiguousColor(arrayOfPic, xSeed - 1, ySeed, findColor)
    if ySeed > 0:
#        print("Here 2:", xSeed, ySeed)
        findContiguousColor(arrayOfPic, xSeed, ySeed - 1, findColor)
    if xSeed < len(arrayOfPic) - 1:
#        print("Here 3:", xSeed, ySeed)
        findContiguousColor(arrayOfPic, xSeed + 1, ySeed, findColor)
    if ySeed < len(arrayOfPic[xSeed]) - 1:
#        print("Here 4:", xSeed, ySeed)
        findContiguousColor(arrayOfPic, xSeed, ySeed + 1, findColor)

In [3]:
inputArray = [[10, 10, 20, 10, 10, 20, 10, 10, 20, 10, 10, 20],
          [10, 20, 20, 10, 20, 20, 10, 10, 20, 10, 10, 20],
          [20, 10, 20, 10, 10, 20, 10, 10, 20, 10, 10, 20],
          [20, 10, 20, 10, 20, 20, 10, 10, 20, 10, 10, 30],
          [10, 10, 20, 10, 10, 10, 10, 10, 20, 10, 10, 30],
          [10, 20, 20, 10, 10, 20, 10, 10, 20, 30, 30, 30],
          [10, 20, 20, 10, 20, 20, 10, 10, 20, 30, 10, 20],
          [20, 10, 20, 10, 10, 20, 10, 30, 30, 30, 10, 20],
          [20, 10, 20, 10, 20, 20, 10, 30, 20, 10, 10, 20],
          [10, 10, 20, 10, 10, 30, 30, 30, 20, 10, 10, 20],
          [10, 20, 20, 10, 10, 30, 10, 10, 20, 10, 10, 20],
          [10, 20, 20, 30, 30, 30, 10, 10, 20, 10, 10, 20],
          [20, 10, 20, 30, 10, 20, 10, 10, 20, 10, 10, 20],
          [20, 30, 30, 30, 20, 20, 10, 10, 20, 10, 10, 20],
          [20, 30, 20, 10, 20, 20, 10, 10, 20, 10, 10, 20],
          [30, 30, 20, 10, 20, 20, 10, 10, 20, 10, 10, 20],
          [20, 10, 20, 10, 20, 20, 10, 10, 20, 10, 10, 20],
          [10, 10, 20, 10, 10, 10, 10, 10, 20, 10, 10, 20]]

In [4]:
print(len(inputArray))
print(len(inputArray[0]))

18
12


In [5]:
findContiguousColor(inputArray, xSeed = 13, ySeed = 3, findColor = 30)

( 13 , 3 )
( 12 , 3 )
( 11 , 3 )
( 11 , 4 )
( 11 , 5 )
( 10 , 5 )
( 9 , 5 )
( 9 , 6 )
( 9 , 7 )
( 8 , 7 )
( 7 , 7 )
( 7 , 8 )
( 7 , 9 )
( 6 , 9 )
( 5 , 9 )
( 5 , 10 )
( 5 , 11 )
( 4 , 11 )
( 3 , 11 )
( 13 , 2 )
( 13 , 1 )
( 14 , 1 )
( 15 , 1 )
( 15 , 0 )


In [6]:
# Look for the 60s
print(np.matrix(inputArray))

[[10 10 20 10 10 20 10 10 20 10 10 20]
 [10 20 20 10 20 20 10 10 20 10 10 20]
 [20 10 20 10 10 20 10 10 20 10 10 20]
 [20 10 20 10 20 20 10 10 20 10 10 60]
 [10 10 20 10 10 10 10 10 20 10 10 60]
 [10 20 20 10 10 20 10 10 20 60 60 60]
 [10 20 20 10 20 20 10 10 20 60 10 20]
 [20 10 20 10 10 20 10 60 60 60 10 20]
 [20 10 20 10 20 20 10 60 20 10 10 20]
 [10 10 20 10 10 60 60 60 20 10 10 20]
 [10 20 20 10 10 60 10 10 20 10 10 20]
 [10 20 20 60 60 60 10 10 20 10 10 20]
 [20 10 20 60 10 20 10 10 20 10 10 20]
 [20 60 60 60 20 20 10 10 20 10 10 20]
 [20 60 20 10 20 20 10 10 20 10 10 20]
 [60 60 20 10 20 20 10 10 20 10 10 20]
 [20 10 20 10 20 20 10 10 20 10 10 20]
 [10 10 20 10 10 10 10 10 20 10 10 20]]
