# DFS Iterative using Stack

In [1]:
import numpy as np
from collections import deque

In [2]:
class coordinate:
    
    def __init__(self, xC, yC):
        self.xValue = xC
        self.yValue = yC


In [3]:
def findCCDFS(arrayOfPic, xSeed, ySeed, findColor):
    
    if arrayOfPic[xSeed][ySeed] != findColor:
        return;
    
    pointsVisited = []
    pointsVisited.append(coordinate(xSeed, ySeed))
        
    while pointsVisited:
        visitingNow = pointsVisited.pop()
        # process this point

        if arrayOfPic[visitingNow.xValue][visitingNow.yValue] != findColor:
            continue;
            
        #Print this cell if of the color we are searching for
        if arrayOfPic[visitingNow.xValue][visitingNow.yValue] == findColor:
            arrayOfPic[visitingNow.xValue][visitingNow.yValue] = 2 * findColor # Change the color so that we don't go into a recursive loop
            print("(", visitingNow.xValue, ",", visitingNow.yValue, ")")
            
        if visitingNow.xValue > 0:
            pointsVisited.append(coordinate(visitingNow.xValue - 1, visitingNow.yValue))
            
        if visitingNow.yValue > 0:
            pointsVisited.append(coordinate(visitingNow.xValue, visitingNow.yValue - 1))
            
        if visitingNow.xValue < len(arrayOfPic) - 1:
            pointsVisited.append(coordinate(visitingNow.xValue + 1, visitingNow.yValue))
            
        if visitingNow.yValue < len(arrayOfPic[0]) - 1:
            pointsVisited.append(coordinate(visitingNow.xValue, visitingNow.yValue + 1))
        


In [4]:
inputArray = [[1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2],
          [1, 2, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2],
          [2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2],
          [2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 5],
          [1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 5],
          [1, 2, 2, 1, 1, 2, 1, 1, 2, 5, 5, 5],
          [1, 2, 2, 1, 2, 2, 1, 1, 2, 5, 1, 2],
          [2, 1, 2, 1, 1, 2, 1, 5, 5, 5, 1, 2],
          [2, 1, 2, 1, 2, 2, 1, 5, 2, 1, 1, 2],
          [1, 1, 2, 1, 1, 5, 5, 5, 2, 1, 1, 2],
          [1, 2, 2, 1, 1, 5, 1, 1, 2, 1, 1, 2],
          [1, 2, 2, 5, 5, 5, 1, 1, 2, 1, 1, 2],
          [2, 1, 2, 5, 1, 2, 1, 1, 2, 1, 1, 2],
          [2, 5, 5, 5, 2, 2, 1, 1, 2, 1, 1, 2],
          [2, 5, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2],
          [5, 5, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2],
          [2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2],
          [1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2]]

In [5]:
print(len(inputArray))
print(len(inputArray[0]))

18
12


In [6]:
findCCDFS(inputArray, xSeed = 13, ySeed = 3, findColor = 5)

( 13 , 3 )
( 13 , 2 )
( 13 , 1 )
( 14 , 1 )
( 15 , 1 )
( 15 , 0 )
( 12 , 3 )
( 11 , 3 )
( 11 , 4 )
( 11 , 5 )
( 10 , 5 )
( 9 , 5 )
( 9 , 6 )
( 9 , 7 )
( 8 , 7 )
( 7 , 7 )
( 7 , 8 )
( 7 , 9 )
( 6 , 9 )
( 5 , 9 )
( 5 , 10 )
( 5 , 11 )
( 4 , 11 )
( 3 , 11 )


In [7]:
# Look for the 10s
print(np.matrix(inputArray))

[[ 1  1  2  1  1  2  1  1  2  1  1  2]
 [ 1  2  2  1  2  2  1  1  2  1  1  2]
 [ 2  1  2  1  1  2  1  1  2  1  1  2]
 [ 2  1  2  1  2  2  1  1  2  1  1 10]
 [ 1  1  2  1  1  1  1  1  2  1  1 10]
 [ 1  2  2  1  1  2  1  1  2 10 10 10]
 [ 1  2  2  1  2  2  1  1  2 10  1  2]
 [ 2  1  2  1  1  2  1 10 10 10  1  2]
 [ 2  1  2  1  2  2  1 10  2  1  1  2]
 [ 1  1  2  1  1 10 10 10  2  1  1  2]
 [ 1  2  2  1  1 10  1  1  2  1  1  2]
 [ 1  2  2 10 10 10  1  1  2  1  1  2]
 [ 2  1  2 10  1  2  1  1  2  1  1  2]
 [ 2 10 10 10  2  2  1  1  2  1  1  2]
 [ 2 10  2  1  2  2  1  1  2  1  1  2]
 [10 10  2  1  2  2  1  1  2  1  1  2]
 [ 2  1  2  1  2  2  1  1  2  1  1  2]
 [ 1  1  2  1  1  1  1  1  2  1  1  2]]


In [8]:
inputArray2 = [[1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2],
          [1, 2, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2],
          [2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2],
          [2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 5],
          [1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 5],
          [1, 2, 2, 1, 1, 2, 1, 1, 2, 5, 5, 5],
          [1, 2, 2, 1, 2, 2, 1, 1, 2, 5, 1, 2],
          [2, 1, 2, 1, 1, 2, 1, 5, 5, 5, 1, 2],
          [2, 1, 2, 1, 2, 2, 1, 5, 2, 1, 1, 2],
          [1, 1, 2, 1, 1, 5, 5, 5, 2, 1, 1, 2],
          [1, 2, 2, 1, 1, 5, 1, 1, 2, 1, 1, 2],
          [1, 2, 2, 5, 5, 5, 1, 1, 2, 1, 1, 2],
          [2, 1, 2, 5, 1, 2, 1, 1, 2, 1, 1, 2],
          [2, 5, 2, 5, 2, 2, 1, 1, 2, 1, 1, 2],
          [2, 5, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2],
          [5, 5, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2],
          [2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2],
          [1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2]]

In [9]:
findCCDFS(inputArray2, xSeed = 13, ySeed = 3, findColor = 5)

( 13 , 3 )
( 12 , 3 )
( 11 , 3 )
( 11 , 4 )
( 11 , 5 )
( 10 , 5 )
( 9 , 5 )
( 9 , 6 )
( 9 , 7 )
( 8 , 7 )
( 7 , 7 )
( 7 , 8 )
( 7 , 9 )
( 6 , 9 )
( 5 , 9 )
( 5 , 10 )
( 5 , 11 )
( 4 , 11 )
( 3 , 11 )


In [10]:
# Look for the 10s
print(np.matrix(inputArray2))

[[ 1  1  2  1  1  2  1  1  2  1  1  2]
 [ 1  2  2  1  2  2  1  1  2  1  1  2]
 [ 2  1  2  1  1  2  1  1  2  1  1  2]
 [ 2  1  2  1  2  2  1  1  2  1  1 10]
 [ 1  1  2  1  1  1  1  1  2  1  1 10]
 [ 1  2  2  1  1  2  1  1  2 10 10 10]
 [ 1  2  2  1  2  2  1  1  2 10  1  2]
 [ 2  1  2  1  1  2  1 10 10 10  1  2]
 [ 2  1  2  1  2  2  1 10  2  1  1  2]
 [ 1  1  2  1  1 10 10 10  2  1  1  2]
 [ 1  2  2  1  1 10  1  1  2  1  1  2]
 [ 1  2  2 10 10 10  1  1  2  1  1  2]
 [ 2  1  2 10  1  2  1  1  2  1  1  2]
 [ 2  5  2 10  2  2  1  1  2  1  1  2]
 [ 2  5  2  1  2  2  1  1  2  1  1  2]
 [ 5  5  2  1  2  2  1  1  2  1  1  2]
 [ 2  1  2  1  2  2  1  1  2  1  1  2]
 [ 1  1  2  1  1  1  1  1  2  1  1  2]]
